### ISSUE TITLE
Error when running addmember.py

### ISSUE THREAD

**Issue by castipo** [south1907/addmember-telegram#10]
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 3 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 4 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 5 at connecting failed: TimeoutError: 
WARNING:telethon.network.mtprotosender:Attempt 6 at connecting failed: TimeoutError: 
Traceback (most recent call last):
  File "C:\Users\muham\Desktop\addmember-telegram-master\addmember.py", line 45, in <module>
    client.connect()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\client\telegrambaseclient.py", line 486, in connect
    proxy=self._proxy
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\network\mtprotosender.py", line 123, in connect
    await self._connect()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\network\mtprotosender.py", line 248, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

**Comment by vijaykrishna0** [comment]
Bro I am noob at this can you do this for me. I can help you in return too. Text me at t.me/vijaykrishna00
