### ISSUE TITLE
Vary Good Effort But Members Not Adding

### ISSUE THREAD

**Issue by Duckonice** [south1907/addmember-telegram#25]
Well Done For Your Good Effort But sucessfully Run inti_session And get_data ,finally Whan Running Adder Than Members not adding to targeted group please upload A video if you can thanks

**Comment by south1907** [comment]
Can you describe error?
Screenshot error?

**Comment by leonardojanisze** [comment]
Same error here:
Error Fooling cmnr
Traceback (most recent call last):
  File "add_member.py", line 141, in <module>
    client(InviteToChannelRequest(target_group_entity,[user_to_add]))
  File "/home/sala/.local/lib/python3.7/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/sala/.local/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/sala/.local/lib/python3.7/site-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by InviteToChannelRequest)

**Comment by south1907** [comment]
Note: If your account blocked, get link https://web.telegram.org/#/im?p=@SpamBot and chat /start to see time released

**Comment by leonardojanisze** [comment]
> Note: If your account blocked, get link https://web.telegram.org/#/im?p=@SpamBot and chat /start to see time released

My account is ok!
Is some problem with "source group", other groups workin... But someones not :/

**Comment by south1907** [comment]
Error Fooling. Telegram block your Account because Spam.
You need add more account
