### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by Rajaghosh0007** [south1907/addmember-telegram#27]
"C:\Users\Amiya Kumar Ghosh\PycharmProjects\pythonProject5\venv\Scripts\python.exe" "C:/Users/Amiya Kumar Ghosh/Desktop/New folder (6)/addmember-telegram-master/add_member.py"
C:\Users\Amiya Kumar Ghosh\Desktop\New folder (6)\addmember-telegram-master
Total account: 1
+12168151042 login success
remain client: 1
current_index: 0
Error Fooling cmnr
remove client: +12168151042
remain client: 0
END: accounts is empty
disconnect
total: 0
total time: 0:00:03.925931
Traceback (most recent call last):
  File "C:/Users/Amiya Kumar Ghosh/Desktop/New folder (6)/addmember-telegram-master/add_member.py", line 141, in <module>
    client(InviteToChannelRequest(target_group_entity,[user_to_add]))
  File "C:\Users\Amiya Kumar Ghosh\PycharmProjects\pythonProject5\venv\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Amiya Kumar Ghosh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Amiya Kumar Ghosh\PycharmProjects\pythonProject5\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Amiya Kumar Ghosh\PycharmProjects\pythonProject5\venv\lib\site-packages\telethon\client\users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by InviteToChannelRequest)

Process finished with exit code 0

**Comment by Rahul-Baba** [comment]
Try other number

**Comment by Rajaghosh0007** [comment]
how to add multiple account in config.json

**Comment by Rajaghosh0007** [comment]
> Try other number
how to add multiple account in config.json

**Comment by south1907** [comment]
`accounts`: list account Telegram
please create array accounts

**Comment by Rajaghosh0007** [comment]
I am try to create array account..but i am failed please help me.. to configure config.json array account...

**Comment by south1907** [comment]
{
	"group_target": 1398120166,
	"group_source": 1490302444,
	"accounts": [
		{
			"phone": "+84XXXX",
			"api_id": 1234566,
			"api_hash": "57c6f3c72c2f21676d53be2eXXXXXX"
		},
               {
			"phone": "+84XXXX",
			"api_id": 1234566,
			"api_hash": "57c6f3c72c2f21676d53be2eXXXXXX"
		}
	]
}

**Comment by Rajaghosh0007** [comment]
Thank you so much sir...
