### ISSUE TITLE
Error when add member

### ISSUE THREAD

**Issue by vinh-nq** [south1907/addmember-telegram#30]
**I got this error when running the program and it will delete my client instead of trying with another member. I stopped running for 1 day to make sure list accounts wasn't blocked for spam.**

`Error other
Traceback (most recent call last):
  File "add_member.py", line 141, in <module>
    client(InviteToChannelRequest(target_group_entity,[user_to_add]))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telethon\client\users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.UserNotMutualContactError: The provided user is not a mutual contact (caused by InviteToChannelRequest)`

Thanks you for support

**Comment by Rahul-Baba** [comment]
Joi group before add members

**Comment by south1907** [comment]
Có thể có 1 vài người cài đặt chế độ riêng tư, chỉ có bạn chung mới add được vào.

**Comment by vinh-nq** [comment]
> Có thể có 1 vài người cài đặt chế độ riêng tư, chỉ có bạn chung mới add được

**Comment by vinh-nq** [comment]
> > Có thể có 1 vài người cài đặt chế độ riêng tư, chỉ có bạn chung mới add được

Vậy có thể cho chương trình chạy tiếp qua member khác nhưng ko bị dừng được không?
