### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by ghostbrucewayne** [south1907/addmember-telegram#44]
Traceback (most recent call last):
  File "add_member.py", line 51, in <module>
    client.start()
  File "C:\Users\Rouna\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\Rouna\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\Rouna\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\auth.py", line 140, in _start
    await self.connect()
  File "C:\Users\Rouna\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\telegrambaseclient.py", line 536, in connect
    self.session.auth_key = self._sender.auth_key
  File "C:\Users\Rouna\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\sessions\sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "C:\Users\Rouna\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\sessions\sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked

**Comment by DanielTheGeek** [comment]
Restarting your system should fix this
