### ISSUE TITLE
a bug in Telethon

### ISSUE THREAD

**Issue by alabeb** [south1907/addmember-telegram#63]
please advise 

PS C:\Users\user\Desktop\addmember-telegram-master> python init_session.py 
+201007154999
Login success
ERROR:telethon.client.updates:Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\telethon\client\updates.py", line 339, in _update_loop
    updates = await asyncio.wait_for(self._updates_queue.get(), deadline_delay)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError
PS C:\Users\user\Desktop\addmember-telegram-master>

**Comment by nimma0001** [comment]
Not using await in login will fix
