### ISSUE TITLE
I'm always using it well :)

### ISSUE THREAD

**Issue by mintolkim** [south1907/addmember-telegram#78]
Traceback (most recent call last):
  File "c:\set up\addmember-telegram-master\get_members.py", line 39, in <module>
    data = get_member_by_group_username(client, group_source)
  File "c:\set up\addmember-telegram-master\utils.py", line 26, in get_member_by_group_username
    entity = client.get_entity(group_username)
  File "C:\Python39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\telethon\client\users.py", line 335, in get_entity
    result.append(await self._get_entity_from_string(x))
  File "C:\Python39\lib\site-packages\telethon\client\users.py", line 574, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "가나다라"

Thanks to Mr. Heva, I always get help. However, Korean is not recognized in this update. I'd appreciate it if you could help me.

ps. Is it possible to use the group_id as in the last update?

**Comment by south1907** [comment]
Your group name is Korean, isn't it?
I will update to use the group_id. Please followup my process in https://github.com/users/south1907/projects/2
And you can request something features in here: https://github.com/south1907/addmember-telegram/discussions/72

**Comment by south1907** [comment]
Done in https://github.com/south1907/addmember-telegram/commit/e226b3769b949e696b147ede998d3c1db491f24f

**Comment by south1907** [comment]
@mintolkim, in file config.json, you can replace "group_source": 1234567
It must is number (not string)

**Comment by mintolkim** [comment]
Thanks you ;)
